"""
Django settings for watchcase_tracker project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Console encoding safety.
# On Windows / IIS (wfastcgi) the stdout/stderr streams default to the legacy
# cp1252 codec. Any diagnostic print() containing non-ASCII characters (e.g.
# status emojis used across several views) then raises UnicodeEncodeError,
# which surfaces to the client as an HTTP 500 with an HTML error page.
# Force UTF-8 with a safe error handler so those writes can never crash a
# request. Guarded because some hosting stdout objects lack reconfigure().
# ---------------------------------------------------------------------------
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding='utf-8', errors='backslashreplace')
    except (AttributeError, ValueError):
        pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project root so .env is picked up even
# when Django is launched from a different working directory (for example IIS).
load_dotenv(BASE_DIR / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gjye57-rx)^o3)f$ix_jy#802*56@oljtx1zrpo6_$-hzvb#mv'

# SECURITY WARNING: don't run with debug turned on in production!
# Driven by the DJANGO_DEBUG environment variable (defaults to False so the
# production IIS deployment is always safe). With DEBUG=True Django keeps every
# executed SQL statement in connection.queries for the life of the worker
# process, which on a long-lived IIS worker leaks memory and makes every
# request progressively slower (root cause of the escalating login latency).
# Set DJANGO_DEBUG=True in your local .env for development.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').strip().lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [
    "trackandtrace.titan.in",
    "192.168.1.2",
    "localhost",
    "127.0.0.1",
    ".devtunnels.ms",
]

# Required for Django 4.0+ CSRF Origin validation.
# Extend this list with production hostname/IP when deploying.
CSRF_TRUSTED_ORIGINS = [
    "https://trackandtrace.titan.in",
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1',
    'http://localhost',
    'https://*.devtunnels.ms',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'csp',
    
    # ownapps
    'modelmasterapp',
    'adminportal',
    'DayPlanning',
    'InputScreening',
    'Brass_QC',
    'BrassAudit',
    'IQF',
    'Jig_Loading',
    'Jig_Unloading',
    'JigUnloading_Zone2',
    'Inprocess_Inspection',
    'Nickel_Inspection',
    'nickel_inspection_zone_two',
    'Nickel_Audit',
    'nickel_audit_zone_two',
    'Recovery_DP',
    'Recovery_IS',
    'Recovery_Brass_QC',
    'Recovery_BrassAudit',
    'Recovery_IQF',
    'ReportsModule',
    'SpiderSpindle_Z1',
    'SpiderSpindle_Z2',
    'SOPManagement',
    'social_django',
]

# AccountLockoutBackend extends the default ModelBackend and additionally
# enforces the account lockout policy (lock after 5 consecutive failed logins).
AUTHENTICATION_BACKENDS = [
    'adminportal.auth_backends.AccountLockoutBackend',
]

# Ensure social login redirects to the dashboard
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/accounts/login/'
SOCIAL_AUTH_LOGIN_URL = '/accounts/login/'

# social-auth pipeline: include our linker function
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'watchcase_tracker.sso_pipeline.link_sso_by_email_or_username',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

MIDDLEWARE = [
    # First in the chain so it wraps everything below it (security, session,
    # auth, view, template) and can attribute the full request time to a
    # per-request breakdown. See watchcase_tracker/perf_logger.py.
    'watchcase_tracker.middleware.performance_middleware.PerformanceProfilerMiddleware',
    'adminportal.middleware.BlockOptionsMiddleware',
    # VAPT #13/#33: strip version-disclosure headers (Server, X-Powered-By, etc.)
    'adminportal.middleware.SecurityHeadersMiddleware',
    # VAPT #35: restrict /admin/ to ADMIN_IP_ALLOWLIST
    'adminportal.middleware.AdminIPRestrictionMiddleware', # Django admin panel restricted in Titan Server
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # SafeSessionMiddleware = Django's SessionMiddleware + graceful handling of
    # SessionInterrupted (session deleted mid-request by a concurrent
    # logout/login or expiry) instead of an error page.
    'adminportal.middleware.SafeSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Idle-session fix: convert login-page redirects into JSON 401
    # (code=SESSION_EXPIRED) for fetch/AJAX requests so scan/validate calls
    # show a proper "session expired" alert instead of "Validation Error".
    'adminportal.middleware.SessionExpiredAjaxMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'adminportal.middleware.CSPMiddleware',
    'adminportal.middleware.LoginLatencyMiddleware',
    # Auto-logs-out a user's older session the moment a newer login lands
    # elsewhere (adminportal.signals.enforce_single_session_on_login records
    # the new session; this middleware enforces it on every subsequent
    # request from the older browser/device). Must run after
    # AuthenticationMiddleware (needs request.user/session) and before
    # ModuleAccessMiddleware (stale sessions must never reach business logic).
    'adminportal.middleware.SingleSessionMiddleware',
    'adminportal.middleware.ModuleAccessMiddleware',
    'middleware.forbidden_redirect.ForbiddenToLoginMiddleware',
    'watchcase_tracker.middleware.latency_middleware.LatencyMiddleware',
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
AUTH_LOGIN_TEMPLATE = 'login.html'

# ---------------------------------------------------------------------------
# VAPT Fix #35 — Admin IP Allow-List
# Only IPs listed here can reach the Django /admin/ interface.
# In production, restrict this to your management network / VPN CIDR.
# An empty list blocks everyone except localhost (safe default).
# ---------------------------------------------------------------------------
ADMIN_IP_ALLOWLIST = [
    '127.0.0.1',
    '::1',
    '192.168.1.2',   # local management workstation — change for production
]

ROOT_URLCONF = 'watchcase_tracker.urls'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'static/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'watchcase_tracker.context_processors.csp_nonce',
                'adminportal.context_processors.user_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'watchcase_tracker.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # Disables DRF's schema/metadata response on OPTIONS requests.
    # No CORS or API discovery is required in this application.
    'DEFAULT_METADATA_CLASS': None,
    'DEFAULT_THROTTLE_RATES': {
        'user': '60/min',
    },
}


# Dev Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'trackandtrace2026',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
} 

# UAT Database
"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'watchcasetrack',
        'USER':'postgres',
        'PASSWORD':'postgres',
        'HOST':'127.0.0.1',
        'PORT':'5432',
        'CONN_MAX_AGE':60,
    }
} """

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'watchcase_tracker.hashers.TTTFastPBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Cache backend — in-process per worker.
# To share across Gunicorn workers (recommended for production scale-out),
# replace with a Redis backend:
#   pip install django-redis
#   CACHES = {'default': {'BACKEND': 'django_redis.cache.RedisCache',
#                         'LOCATION': 'redis://127.0.0.1:6379/1'}}
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'ttt-default',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 2000,
        },
    },
    # Permission-critical cache (is_admin / user groups / allowed modules —
    # adminportal.services). LocMemCache is per-worker-process: under the
    # IIS deployment (multiple worker processes, no shared memory) a cache
    # invalidation performed by the worker handling an admin's group/role
    # edit never reaches the OTHER worker processes, which keep serving a
    # stale is_admin value to the affected user for up to USER_MODULE_CACHE_TTL
    # (5 min) — surfacing as the header Settings icon disappearing until the
    # user fully logs out and back in. DatabaseCache is shared by every
    # worker process (backed by Postgres, the existing DB), so an
    # invalidation from any process is immediately visible to all others.
    'permissions': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'ttt_permissions_cache',
        'TIMEOUT': 300,
    },
}

# cached_db reads the session from the in-process cache on warm hits,
# falling back to PostgreSQL only on a miss. This removes one DB round-trip
# from every authenticated request compared to the plain 'db' backend.
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
# True = sliding inactivity timeout: every request refreshes the session
# cookie, so users are only logged out after SESSION_COOKIE_AGE seconds of
# real inactivity (not a hard cutoff measured from login time).
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_HTTPONLY = False
# Default to HTTPS cookies; explicitly opt out only for local HTTP development.
CSRF_COOKIE_SECURE = os.environ.get("DJANGO_COOKIE_SECURE", "true").strip().lower() != "false"
CSRF_COOKIE_SAMESITE = "Lax"

# SESSION_COOKIE_SECURE = False   # Issue #4: require HTTPS for session cookie
#
# Perf/session fix: this used to be hard-tied to DEBUG (False if DEBUG else
# True), which silently assumes production == always-HTTPS. ALLOWED_HOSTS
# includes "192.168.1.2" (a plain-IP host), so if that host is ever reached
# over HTTP instead of the HTTPS domain, a Secure cookie is never sent back
# by the browser - the session never "sticks", every request looks logged
# out, and the session-expired alert fires constantly even for a fresh
# login. DJANGO_SESSION_COOKIE_SECURE lets ops correct this from the
# deployed .env alone (no code/web.config change) if that turns out to be
# the case; unset, behavior is unchanged from before.
SESSION_COOKIE_SECURE = os.environ.get(
    'DJANGO_SESSION_COOKIE_SECURE',
    'False' if DEBUG else 'True',
).strip().lower() in ('1', 'true', 'yes', 'on')
SESSION_COOKIE_AGE = 900       #15 -minute session timeout (was 86400 sec / 24 h)

# ---------------------------------------------------------------------------
# CSRF cookie hardening (VAPT / Burp finding: "Cookie without HttpOnly flag
# set" — csrftoken).
#
# HttpOnly: the csrftoken cookie is never read by legitimate client code any
# more — the token is taken from the {% csrf_token %} hidden field / the
# <meta name="csrf-token"> tag by static/js/csrf_utils.js, which also injects
# the X-CSRFToken header on every same-origin state-changing fetch()/XHR.
# Django still validates writes by comparing that header (or the form field)
# against the cookie the browser sends automatically, so HttpOnly is safe.
#
# Secure: mirror the session-cookie logic so the flag is only relaxed for a
# genuine plain-HTTP deployment (controlled by the same env var); on the
# HTTPS production host the cookie is Secure.
# ---------------------------------------------------------------------------
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = os.environ.get(
    'DJANGO_SESSION_COOKIE_SECURE',
    'False' if DEBUG else 'True',
).strip().lower() in ('1', 'true', 'yes', 'on')

# ---------------------------------------------------------------------------
# HSTS — HTTP Strict-Transport-Security (VAPT Finding #7)
# Django's SecurityMiddleware injects this header on every HTTPS response.
# max-age=63072000 = 2 years (recommended); includeSubDomains + preload for
# full protection. Do NOT enable SECURE_SSL_REDIRECT here — IIS handles the
# HTTP→HTTPS redirect; doing it in Django as well would cause a redirect loop.
# SECURE_PROXY_SSL_HEADER tells Django to trust the X-Forwarded-Proto header
# that IIS sets when it forwards a TLS-terminated request to the Django app.
# ---------------------------------------------------------------------------
SECURE_HSTS_SECONDS = 63072000          # 2 years
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
#
# Off by default (matches the previous commented-out state - no behavior
# change unless explicitly enabled). If IIS is confirmed to forward
# X-Forwarded-Proto for TLS-terminated requests, set
# DJANGO_TRUST_X_FORWARDED_PROTO=True in the server's .env so
# request.is_secure() correctly reports True behind IIS. This affects the
# post-OTP-login redirect safety check (adminportal/views.py:
# verify_email_otp -> url_has_allowed_host_and_scheme(require_https=...))
# and any other code that branches on request.is_secure().
if os.environ.get('DJANGO_TRUST_X_FORWARDED_PROTO', 'False').strip().lower() in ('1', 'true', 'yes', 'on'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ENABLE_MICROSOFT_LOGIN = True
ENABLE_LOGIN_LATENCY_LOGS = False
ENABLE_DASHBOARD_LATENCY_LOGS = False

# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'watchcase_tracker.staticfiles_finders.ExcludeDRFBootstrapFinder',
]

MODEL_IMAGE_MAX_UPLOAD_SIZE = 10 * 1024 * 1024

# Maximum size (bytes) accepted for an uploaded SOP PDF document.
SOP_FILE_MAX_UPLOAD_SIZE = 20 * 1024 * 1024

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Minimal logging
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)  # for the security audit log
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
            'datefmt': '%d/%b/%Y %I:%M:%S %p',
        },
        'security': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
        # Kept minimal on purpose: perf_logger already formats the
        # REQUEST_ID | PATH | STAGE | DURATION | DB_QUERIES | STATUS line;
        # this formatter just prefixes it with a timestamp.
        'performance': {
            'format': '{asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'security_console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'security',
        },
        'security_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security_audit.log'),
            'formatter': 'security',
        },
        # Separate from security/django logs on purpose - see
        # watchcase_tracker/perf_logger.py and middleware/performance_middleware.py.
        'performance_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'application_performance.log'),
            'formatter': 'performance',
        },
    },
    'loggers': {
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
        # Audit trail for login failures, account lock and unlock events.
        'security': {
            'handlers': ['security_console', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Per-request stage breakdown for slow requests (PerformanceProfilerMiddleware).
        'performance': {
            'handlers': ['performance_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Microsoft (Entra ID) / MSAL settings
MSAL_CLIENT_ID = os.getenv("MSAL_CLIENT_ID", "00855866-7b9b-498f-b1d5-d8aae7c9680e")
MSAL_CLIENT_SECRET = os.getenv("MSAL_CLIENT_SECRET")
# MSAL_TENANT_ID = os.getenv("MSAL_TENANT_ID", "common")
# The Azure App Registration's Redirect URI is registered WITH a trailing
# slash. _get_redirect_uri() (watchcase_tracker/sso.py) falls back to
# reverse('microsoft_callback') when this is unset, and that URL name is
# bound to the non-trailing-slash route in urls.py, which built a redirect
# URI that Azure rejected with AADSTS50011 ("... had a trailing slash").
# Setting this explicitly makes the sent redirect_uri match what's
# registered in Azure, independent of which urls.py route owns the name.
MSAL_REDIRECT_PATH = "/auth/microsoft/callback/"



MSAL_TENANT_ID = os.getenv("MSAL_TENANT_ID","7cc91c38-648e-4ce2-a4e4-517ae39fc189",).strip()

# Optional fixed origin (scheme+host[:port]) for the OAuth redirect URI, e.g.
# "http://localhost:8000" or "https://titan.example.com". Pinning to one
# Azure-registered URI avoids AADSTS50011 mismatches from how a browser
# reaches the app (127.0.0.1 vs localhost, etc). This used to be assigned
# twice - a "https://trackandtrace.titan.in" default immediately clobbered by
# an unconditional "http://localhost:8000" default below it - so every
# environment without an explicit env var silently sent Microsoft a
# localhost redirect_uri. If the browser was on a different origin than that
# (e.g. 127.0.0.1:8000), Microsoft's callback lands on an origin that never
# receives the login page's session cookie, so the saved msal_states never
# arrive and the callback raises "State mismatch or missing" even though the
# login itself was legitimate. Deriving the default from DEBUG keeps a single
# source of truth: local/dev pins to localhost:8000 (access the app via that
# exact host, not 127.0.0.1, so the session cookie's origin matches),
# production pins to the deployed domain, and MSAL_REDIRECT_URI_BASE still
# lets ops override either from the .env alone.
MSAL_REDIRECT_URI_BASE = os.getenv(
    "MSAL_REDIRECT_URI_BASE",
    "http://localhost:8000" if DEBUG else "https://trackandtrace.titan.in",
).strip().rstrip("/")
MSAL_SCOPES = ["User.Read"]
